In [1]:
import numpy as np

In [5]:
a = np.arange(6)

In [6]:
type(a)

numpy.ndarray

In [7]:
a

array([0, 1, 2, 3, 4, 5])

In [8]:
a[:]

array([0, 1, 2, 3, 4, 5])

In [11]:
a2 = a[np.newaxis,:]

In [12]:
a2.shape

(1, 6)

In [13]:
a.shape

(6,)

In [17]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [18]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
a[0,2]

3

In [20]:
a[0]

array([1, 2, 3, 4])

In [21]:
a = np.array([1, 2, 3])

In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.ones(3)

array([1., 1., 1.])

In [24]:
np.empty(5)

array([1.00101366e-311, 1.00103355e-311, 1.00103355e-311, 1.00101271e-311,
       1.22383816e-307])

In [25]:
np.arange(1,5)

array([1, 2, 3, 4])

In [26]:
np.arange(2,8,2)

array([2, 4, 6])

In [28]:
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [34]:
b = np.ones(2, dtype=np.int64)

In [35]:
b

array([1, 1], dtype=int64)

In [36]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [37]:
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [38]:
arr = np.sort(arr)

In [39]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [40]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [41]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [42]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [43]:
x

array([[1, 2],
       [3, 4]])

In [44]:
y

array([[5, 6]])

In [45]:
np.concatenate((x,y))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [46]:
np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [48]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [49]:
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [51]:
array_example.ndim

3

In [52]:
array_example.size

24

In [54]:
array_example.shape

(3, 2, 4)

In [55]:
a = np.arange(6)

In [57]:
a

array([0, 1, 2, 3, 4, 5])

In [61]:
a = a.reshape(3,2)

In [62]:
a.shape

(3, 2)

In [63]:
a = np.arange(6)

In [64]:
print(a)

[0 1 2 3 4 5]


In [65]:
b = a.reshape(3, 2)    

In [66]:
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [67]:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [68]:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [69]:
a = np.array([1, 2, 3, 4, 5, 6])

In [70]:
a.shape

(6,)

In [71]:
a2 = a[np.newaxis, :]

In [72]:
a2.shape

(1, 6)

In [73]:
b = np.expand_dims(a, axis=1)

In [74]:
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [75]:
c = np.expand_dims(a, axis=0)

In [76]:
c

array([[1, 2, 3, 4, 5, 6]])

In [77]:
data = np.array([1, 2, 3])

In [79]:
data

array([1, 2, 3])

In [80]:
data[0]

1

In [81]:
data[0:2]

array([1, 2])

In [82]:
data[1:]

array([2, 3])

In [83]:
data[-2:]

array([2, 3])

In [84]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [85]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [86]:
a < 5

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [87]:
b = 2

In [89]:
b > 5

False

In [93]:
a[a<5]

array([1, 2, 3, 4])

In [94]:
a[a >= 5]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [95]:
 a%2 == 0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [96]:
a[a%2 ==0]

array([ 2,  4,  6,  8, 10, 12])

In [97]:
np.nonzero(a < 5)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))

In [98]:
B = np.nonzero(a < 5)

In [99]:
B

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))

In [100]:
list(zip(B[0],B[1]))

[(0, 0), (0, 1), (0, 2), (0, 3)]

In [101]:
a[(a > 2) & (a < 11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [105]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [106]:
arr1 = a[3:8]

In [107]:
arr1

array([4, 5, 6, 7, 8])

In [108]:
a1 = np.array([[1, 1],
               [2, 2]])
a2 = np.array([[3, 3],
               [4, 4]])

In [109]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [110]:
np.concatenate((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [112]:
a = np.arange(1,15)

In [113]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [114]:
a.reshape(2,7)

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [115]:
x = np.arange(1,25).reshape(2,12)

In [116]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [121]:
np.hsplit(x,(3,6,9))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5,  6],
        [16, 17, 18]]),
 array([[ 7,  8,  9],
        [19, 20, 21]]),
 array([[10, 11, 12],
        [22, 23, 24]])]

In [123]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [124]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [125]:
a[0,:]

array([1, 2, 3, 4])

In [126]:
b = a[0,:]

In [127]:
b

array([1, 2, 3, 4])

In [128]:
b[0] = 99

In [129]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [130]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [133]:
b = a[0,:].copy()

In [134]:
b

array([1, 2, 3, 4])

In [135]:
b[0] = 99

In [136]:
b

array([99,  2,  3,  4])

In [137]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [138]:
data =  np.array([1, 2])

In [140]:
ones = np.ones(2, dtype=int)

In [141]:
data

array([1, 2])

In [142]:
ones

array([1, 1])

In [143]:
data + ones

array([2, 3])

In [144]:
data - ones

array([0, 1])

In [145]:
data * ones

array([1, 2])

In [146]:
data / ones

array([1., 2.])

In [147]:
ones / data

array([1. , 0.5])

In [148]:
a = np.array([1, 2, 3, 4])

In [149]:
a

array([1, 2, 3, 4])

In [150]:
a.sum()

10

In [151]:
b = np.array([[1, 2],[3, 4]])

In [152]:
b

array([[1, 2],
       [3, 4]])

In [153]:
b.sum(axis=0)

array([4, 6])

In [154]:
b

array([[1, 2],
       [3, 4]])

In [155]:
b.sum(axis=1)

array([3, 7])

In [156]:
 a.max()


4

In [157]:
a.min()

1

In [158]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [159]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [160]:
data[0:2, 0]

array([1, 3])

In [161]:
data.max()

6

In [162]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [163]:
np.unique(a)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [166]:
np.unique(a, return_index=True)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14], dtype=int64))

In [167]:
np.unique(a, return_counts=True)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([3, 2, 2, 2, 1, 1, 1, 1, 1, 1], dtype=int64))

In [168]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [169]:
data.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [170]:
data.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

In [171]:
np.flip(data)

array([[6, 5],
       [4, 3],
       [2, 1]])